// Generated by CoffeeScript 1.3.3
(function() {
  var utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  utils = require("./utils");

  module.exports = function(Validator) {
    return (function(_super) {

      __extends(_Class, _super);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.name = "Float";

      _Class.prototype.description = "Makes sure a value is a float";

      _Class.prototype.classNames = ["validate-float"];

      _Class.prototype.defaultOptions = {
        decimalMark: ","
      };

      _Class.prototype.validate = function(value) {
        var regex;
        value = this.sanitize(value);
        regex = new RegExp("\\d+(\\" + this.options.decimalMark + "\\d+)?");
        if (value.replace(regex, "") !== "") {
          return "Must be a number.";
        }
        return true;
      };

      _Class.prototype.sanitize = function(value) {
        if (value.indexOf(".") >= 0 && value.indexOf(",") >= 0) {
          if (value.lastIndexOf(",") > value.lastIndexOf(".")) {
            value = value.replace(/\./g, "");
          } else {
            value = value.replace(/\,/g, "");
          }
        }
        if (value.indexOf(",") >= 0) {
          value = value.replace(/\,/g, ".");
        }
        if (value.indexOf(".") !== value.lastIndexOf(".")) {
          value = value.replace(/\./g, "");
        }
        value = value.replace(/\./g, this.options.decimalMark);
        return utils.trim(value);
      };

      return _Class;

    })(Validator);
  };

}).call(this);
