// Generated by CoffeeScript 1.3.3
(function() {
  var utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  utils = require("./utils");

  module.exports = function(Validator) {
    return (function(_super) {

      __extends(_Class, _super);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.name = "Integer";

      _Class.prototype.description = "Makes sure a value is an integer";

      _Class.prototype.classNames = ["validate-integer"];

      _Class.prototype.validate = function(value) {
        if (value.replace(/\d*/, "") !== "") {
          return "Has to be a number.";
        }
        return true;
      };

      _Class.prototype.sanitize = function(value) {
        return utils.trim(value);
      };

      return _Class;

    })(Validator);
  };

}).call(this);
