// Generated by CoffeeScript 1.3.3
(function() {
  var bonzo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bonzo = require("bonzo");

  module.exports = function(Validator) {
    return (function(_super) {

      __extends(_Class, _super);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.name = "Required";

      _Class.prototype.description = "Makes sure the value is not blank (nothing or spaces).";

      _Class.prototype.classNames = ["required"];

      _Class.prototype.validate = function(sanitizedValue, input) {
        var binput;
        binput = bonzo(input);
        if ((binput.attr("type") === "checkbox" && !binput.is(":checked")) || !sanitizedValue.replace(/\s*/g, "")) {
          return "Can not be blank.";
        }
        return true;
      };

      return _Class;

    })(Validator);
  };

}).call(this);
